### ISSUE TITLE
Chapter 18 - STL - The class 'unique_ptr': example error

### ISSUE THREAD

**Issue by vslash** [fbb-git/cppannotations#3]
In version 10.5, pp 478, the following example : 

```
class Base
{ ... };
class Derived: public Base
{
// assume Derived has a member void process()
};
int main()
{
shared_ptr<Base> bp(new Derived);
static_cast<Derived *>(bp)->process(); // OK!
} // here ~Derived is called: no polymorphism required.
```

lead to:
`error: cannot dynamic_cast 'bp' (of type 'class std::unique_ptr<Base>') to type 'class Derived*' (source is not a pointer)`
using g++ 4.8.4
So:
`static_cast<Derived&>(*bp).process(); // OK!`
should be fine.
B.R.

**Comment by fbb-git** [comment]
Dear Valéry, you wrote:

> ...
> using g++ 4.8.4
> So:
> `static_cast<Derived&>(*bp).process(); // OK!`
> should be fine.
> B.R.

Ah, thanks for the heads-up!

I think there's more fun to that example than just the missing pointer: the
example is inside the unique_ptr section, but refers to a shared_ptr, which is
confusing. Furthermore, the comment at the end of the main function:

```
// here ~Derived is called: no polymorphism required.
```

is partially correct: it is true that no polymorphism is required, but it is
not true that ~Derived is called. To have the destructor called the unique_ptr
definition also must specify a deleter.

The current example can easily be fixed: the following code will appear in the
Annotations' next release, and compiles fine with g++ 6.1.1 (as an aside:
please note that you're mentioning g++ 4.8.4, which by now is a fairly old
release of the g++ compiler. Maybe you should upgrade?)

Anyway, here is the modified example (using in-class implementations for
brevity). The git-sources have already been modified accordingly:

---

#include <iostream>
#include <memory>
using namespace std;

class Base
{  };

class Derived: public Base
{
    // assume Derived has a member void process()
    public:
        void process()
        {
            cout << "process called\n";
        }
        ~Derived()
        {
            cout << "destructor called\n";
        }
        static void deleter(Base _bp)
        {
            delete static_cast<Derived *>(bp);
        }
};
int main()
{
    unique_ptr<Base, void (_)(Base *)> bp(new Derived, &Derived::deleter);
    static_cast<Derived *>(bp.get())->process();

## }

Thanks again!

## 

```
Frank B. Brokken
Center for Information Technology, University of Groningen
(+31) 50 363 9281 
Public PGP key: http://pgp.surfnet.nl
Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
```

**Comment by vslash** [comment]
well noticed.
Thanks to you,
your guide is really amazing and useful,

## 

Valéry
