### ISSUE TITLE
23.1.2 virtual member template example

### ISSUE THREAD

**Issue by louwers** [fbb-git/cppannotations#6]
In 23.1.2, refering to the example given, you write:

> In the example Base declares a virtual void member and Derived defines its overriding function member. In that case `this->member()` in `Derived::Derived` calls, due to member's virtual nature, `Derived::member`. 

However, since `this` is a `Derived<T> *`, `this->member()` will call `Derived<T>::member` regardless of whether `Base<T>::member` is virtual (as can be verified by removing the `virtual` keyword, this produces exactly the same output).

You could fix the demonstration of virtual members of template classes by adding the line `static_cast<Base<T> *>(this)->member();` in `Derived<T>::Derived`, which *will* call a different function depending on whether `Base<T>::member` is virtual.

**Comment by fbb-git** [comment]
Dear Bart, you wrote:
> In 23.1.2, refering to the example given, you write:
> 
> > In the example Base declares a virtual void member and Derived defines its overriding function member. In that case `this->member()` in `Derived::Derived` calls, due to member's virtual nature, `Derived::member`. 
> 
> However, since `this` is a `Derived<T> *`, `this->member()` will call
`Derived<T>::member` regardless of whether `Base<T>::member` is virtual (as
can be verified by removing the `virtual` keyword, this produces exactly the
same output).

Thanks for your contribution. You're absolutely right, and I'll process your
remarks in the next version of the C++ Annotations.

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
